[package]
name = "susbot"
version = "0.1.0"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.8"
clap = { version = "3.0.0", features = ["derive"] }
tokio = {version = "1.15", features = ["macros", "rt-multi-thread"]}
tracing = "0.1.29"
tracing-subscriber = "0.3.5"
rand = "0.8.4"

[dependencies.serenity]
default-features=false
features=["client", "gateway", "rustls_backend", "model", "cache"]
version = "0.10.9"

[features]
