[package]
name = "susbot"
version = "0.1.0"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
pretty_env_logger = "0.4.0"
reqwest = "0.11.8"
structopt = "0.3"
tokio = {version = "1.15", features = ["macros", "rt-multi-thread"]}
rand = "0.8.4"
once_cell = "1.9.0"

[dependencies.serenity]
default-features=false
features=["client", "gateway", "rustls_backend", "model", "cache"]
version = "0.10.9"
