[package]
name = "susbot"
version = "0.2.0"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.9"
clap = { version = "3.0.14", features = ["derive"] }
tokio = {version = "1.16", features = ["macros", "rt-multi-thread"]}
tracing = "0.1.30"
tracing-subscriber = "0.3.8"
rand = "0.8.4"

[dependencies.serenity]
default-features=false
features=["client", "gateway", "rustls_backend", "model", "cache"]
version = "0.10.10"

[features]
